.\"                                      Hey, EMACS: -*- nroff -*-
.\" gtkmonop.6 is copyright 2001 by
.\" Erik Bourget <ebourg@po-box.mcgill.ca>
.\"
.\" This is free documentation, see the latest version of the GNU Free
.\" Documentation License for copying conditions. There is NO warranty.
.\"
.TH GTKMONOP 6 "June 6, 2001" "gtkmonop"
.\" Please adjust this date whenever revising the manpage.
.\"

.SH NAME
gtkmonop \- a monopoly client written with GTK+

.SH SYNOPSIS
.B gtkmonop
.\" .RI [ options ]

.SH DESCRIPTION
This manual page documents briefly the
.B gtkmonop
command.
.PP
\fBgtkmonop\fP is a monopd client written in Gtk+.  monopd is a
Monopoly daemon written by Rob Kaper <cap@capsi.com> in C++,
originally intended to drive his kmonop client.  To check out monopd,
point your favorite browser (the power of Mozilla commands you) to
http://capsi.com/~cap/monopd.
.SH OPTIONS
gtkmonop accepts the following options, besides the usual Gtk+/GNOME
switches:
... No.

.SH HOMEPAGE
http://gtkmonop.sourceforge.net

.SH AUTHOR
This manual page was written by Erik Bourget
<ebourg@po-box.mcgill.ca>, author of gtkmonop.
